# Generated by Django 5.0.3 on 2024-07-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutimage",
            options={
                "verbose_name": "About Image",
                "verbose_name_plural": "About Images",
            },
        ),
        migrations.AlterModelOptions(
            name="aboutmessage",
            options={
                "verbose_name": "About Message",
                "verbose_name_plural": "About Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="case",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Case",
                "verbose_name_plural": "Cases",
            },
        ),
        migrations.AlterModelOptions(
            name="caseimage",
            options={
                "verbose_name": "Case Image",
                "verbose_name_plural": "Case Images",
            },
        ),
        migrations.AlterModelOptions(
            name="vehicle",
            options={"verbose_name": "Vehicle", "verbose_name_plural": "Vehicles"},
        ),
        migrations.AlterModelOptions(
            name="vehicletype",
            options={
                "verbose_name": "Vehicle Type",
                "verbose_name_plural": "Vehicle Types",
            },
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="year",
            field=models.PositiveIntegerField(),
        ),
    ]
