# Generated by Django 5.0.3 on 2024-10-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0004_servicecategory_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
