# Generated by Django 5.0.3 on 2024-10-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0005_alter_service_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutimage",
            name="image_alt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image alt"
            ),
        ),
        migrations.AlterField(
            model_name="aboutmessage",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="case",
            name="preview_image_alt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Priview image alt"
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="caseimage",
            name="image_alt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image alt"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="brand",
            field=models.CharField(max_length=100, verbose_name="Brand"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="model",
            field=models.CharField(max_length=100, verbose_name="Model"),
        ),
    ]
