# Generated by Django 5.0.3 on 2024-10-28 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0007_alter_servicecategory_options_remove_case_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutmessage",
            options={
                "verbose_name": "Повідомлення про нас",
                "verbose_name_plural": "Повідомлення про нас",
            },
        ),
        migrations.AlterModelOptions(
            name="servicecategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Категорія послуг",
                "verbose_name_plural": "Категорії послуг",
            },
        ),
    ]
