# Generated by Django 5.0.3 on 2024-10-28 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0008_alter_aboutmessage_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutmessage",
            options={
                "verbose_name": "About Message",
                "verbose_name_plural": "About Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="servicecategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Service Category",
                "verbose_name_plural": "Service Categories",
            },
        ),
    ]
